### ISSUE TITLE
Pauzování skladeb

### ISSUE THREAD

**Issue by kalich5** [madmaxoft/SkauTan#120]
Když udělám pauzu ve skladbě, a pak zase play pustí se skladba od začátku. Né od toho místa, kde jsem udělal pauzu.

**Comment by madmaxoft** [comment]
Otazkou je, co s tim - je tu nesoulad toho, co ukazuje GUI (poloha prehravace uprostred pisnicky) a co se pak deje. Moznosti:
  - po opetovnem spusteni prehravani prehravat od posledni polohy (tzn. to, co ted' GUI ukazuje)
  - po  zapauzovani smazat ukazatel polohy a zacinat prehravat od zacatku (tzn. opravit GUI)

**Comment by kalich5** [comment]
Podle mě by se to mělo chovat jako klasický přehrávač. Tedy když udělám pauzu, a pak to pustím. Bude to pokračovat tam kde jsem to pauznul.

**Comment by kalich5** [comment]
Už jsem to několikrát použil. Někdo se třeba ptal, co to hraje. Tak to pauznu (abych neřval přes hudbu), řeknu to a pustím to dál

**Comment by madmaxoft** [comment]
Pauznes vsem skladbu, abys jednomu rekl, co hraje? :)
Kvok, tak teda dopisu to rozjeti od posledni pozice. Je to trochu slozitejsi, ale snad to pujde.

**Comment by kalich5** [comment]
Občas se to stane, hrál jsem několikrát kdy tam byli začátečníci. A bylo to prostě potřeba.
