### ISSUE TITLE
Chyba při zpuštění

### ISSUE THREAD

**Issue by kalich5** [madmaxoft/SkauTan#209]
MidiInWinMM::initialize: no MIDI input devices currently available.

Nevím co to je...

**Comment by madmaxoft** [comment]
To je jen varovani od knihovny pro MIDI pristup (pouziva se na ovladani SkauTanu pomoci DJ ovladace, #149). Muzes to ignorovat; hlasi to takhle uz dlouho, ale az ted' po prechodu na CMake se zacala zobrazovat konzole, do ktere jdou vsechny tyhle debug hlasky. Konzoli schovam.

**Comment by kalich5** [comment]
Ok, do aktuální verze se to dostane v noci?

**Comment by madmaxoft** [comment]
Pustil jsem novy build, bude to tam tak za 10 minut.
