### ISSUE TITLE
Sekání hudby

### ISSUE THREAD

**Issue by kalich5** [madmaxoft/SkauTan#54]
Když maximalizuju, minimalizuju programy na počítači, sekne se třeba na půl sekundy hudba.

**Comment by madmaxoft** [comment]
Taky jsem si vsimnul, vypada to na problem primo v Qt Audio modulu. Casem chci vyzkouset platform-specific audio vystupy.

**Comment by madmaxoft** [comment]
Primarni duvod zrejme nalezen - audio output bezi v GUI threadu, takze kdyz GUI thread neco vetsiho resi, tak audio nestiha. Otazkou je, proc je to takhle nesmyslne, ackoliv mu explicitne vytvorim separatni thread a snazim se jej do nej presunout ( https://github.com/madmaxoft/SkauTan/blob/e03458c273401bd67ff7815c2063ceb817f00612/Player.cpp#L48 ).
