### ISSUE TITLE
Next song - nefunguje

### ISSUE THREAD

**Issue by kalich5** [madmaxoft/SkauTan#55]
Dohraje jedna písnička a nepustí se další. Program se sekne a vyskočí hláška že (Neodpovídá)

**Comment by madmaxoft** [comment]
Je stejny problem i s vypnutim behem prehravani - GUI zmizi, ale proces zustane viset.
V `RingBuffer` chybi detekce EndOfFile, takze stale ceka na nove zapsana data, ackoliv uz zadna nikdy neprijdou.
