### ISSUE TITLE
Nefunguje posuvník

### ISSUE THREAD

**Issue by kalich5** [madmaxoft/SkauTan#77]
Posuvník, který ukazuje pohyb v písničce nefunguje. Nijak se neposouvá.

![bez nazvu](https://user-images.githubusercontent.com/8988898/39724078-08ec861e-5248-11e8-8c55-5523352326c4.png)

**Comment by madmaxoft** [comment]
To je divne, mi normalne funguje.
Kazdopadne v ramci #63 se cely posuvnik rusi, takze zaviram :)

![image](https://user-images.githubusercontent.com/4388386/39725972-d4c910cc-524d-11e8-9ccd-a92404a88d86.png)

**Comment by kalich5** [comment]
Ty jo, tak to nechápu proč se mi to takhle neukazuje :-(

**Comment by madmaxoft** [comment]
Protoze to esce neni dodelane a v te tvoji verzi to neni.

**Comment by kalich5** [comment]
aha :D ok
