### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by nunojesus** [madmaxoft/SkauTan#83]
Do you already have someone to help you with the graphic design of the project? I ask this because I have not seen any logotype associated with this project.

**Comment by madmaxoft** [comment]
I don't plan on using much graphics for this project, the aim is to stay simple. The only piece of graphics this project currently uses is the logo of the organization for whom I'm writing the player, Skautské tancování, used as the app icon.

**Comment by nunojesus** [comment]
Ok then, if you need me just say it, if you have other projects that you need my help as graphic designer just say it.
