### ISSUE TITLE
Zvýraznění toho co hraje

### ISSUE THREAD

**Issue by kalich5** [madmaxoft/SkauTan#89]
Hodilo by se, nějak zvýraznit to co hraje. Třeba aby ten řádek byl modrý. Nebo aby tam byla nějaká jasná značka, co hraje.

**Comment by madmaxoft** [comment]
Podbarveni by dost dobre nefungovalo, bilo by se se zvyraznenim toho, co je zrovna vybrane. Znacka, nebo tucne pismo?

**Comment by kalich5** [comment]
Tak tučné písmo a nejlépe i vlevo značka "play" že to hraje. Aby to bylo na první podle vidět.
